// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIuAkfU6cI7LbW3S1msG0jI_KrQTESa7Y',
    appId: '1:1084964136938:ios:7008b11289220332df7493',
    messagingSenderId: '1084964136938',
    projectId: 'weatherapp-20e2c',
    storageBucket: 'weatherapp-20e2c.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIuAkfU6cI7LbW3S1msG0jI_KrQTESa7Y',
    appId: '1:1084964136938:ios:7008b11289220332df7493',
    messagingSenderId: '1084964136938',
    projectId: 'weatherapp-20e2c',
    storageBucket: 'weatherapp-20e2c.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeTe8Q9Ob726eoyqpeYyOtEWHaXg3iaKM',
    appId: '1:1084964136938:web:fab99181e582c44edf7493',
    messagingSenderId: '1084964136938',
    projectId: 'weatherapp-20e2c',
    authDomain: 'weatherapp-20e2c.firebaseapp.com',
    storageBucket: 'weatherapp-20e2c.firebasestorage.app',
    measurementId: 'G-JP0C0CQC80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcOOf4J91w_eQHqK4jx1GFDvi8m7KyCqg',
    appId: '1:1084964136938:android:0fb59f7df00635efdf7493',
    messagingSenderId: '1084964136938',
    projectId: 'weatherapp-20e2c',
    storageBucket: 'weatherapp-20e2c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeTe8Q9Ob726eoyqpeYyOtEWHaXg3iaKM',
    appId: '1:1084964136938:web:746030f222f55517df7493',
    messagingSenderId: '1084964136938',
    projectId: 'weatherapp-20e2c',
    authDomain: 'weatherapp-20e2c.firebaseapp.com',
    storageBucket: 'weatherapp-20e2c.firebasestorage.app',
    measurementId: 'G-NMNJVWXE9R',
  );

}
