// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqYNVvKPDMJkNfphsFs_5fzJg9GjX3SqE',
    appId: '1:507902510908:web:108cf7f797461bf4160039',
    messagingSenderId: '507902510908',
    projectId: 'jbmtraders-ed3d9',
    authDomain: 'jbmtraders-ed3d9.firebaseapp.com',
    storageBucket: 'jbmtraders-ed3d9.firebasestorage.app',
    measurementId: 'G-F14YEMWR9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtDjUikHVrPD_gWjrwCsCd_HETQrGVJDo',
    appId: '1:507902510908:android:5f6ed2d5d62659a7160039',
    messagingSenderId: '507902510908',
    projectId: 'jbmtraders-ed3d9',
    storageBucket: 'jbmtraders-ed3d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkECxx_uEu0jA77ef_KkYspqwmuOK5Kno',
    appId: '1:507902510908:ios:ad2ce417dffde800160039',
    messagingSenderId: '507902510908',
    projectId: 'jbmtraders-ed3d9',
    storageBucket: 'jbmtraders-ed3d9.firebasestorage.app',
    iosBundleId: 'com.example.groceryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkECxx_uEu0jA77ef_KkYspqwmuOK5Kno',
    appId: '1:507902510908:ios:ad2ce417dffde800160039',
    messagingSenderId: '507902510908',
    projectId: 'jbmtraders-ed3d9',
    storageBucket: 'jbmtraders-ed3d9.firebasestorage.app',
    iosBundleId: 'com.example.groceryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqYNVvKPDMJkNfphsFs_5fzJg9GjX3SqE',
    appId: '1:507902510908:web:2bc307b9503b6cdb160039',
    messagingSenderId: '507902510908',
    projectId: 'jbmtraders-ed3d9',
    authDomain: 'jbmtraders-ed3d9.firebaseapp.com',
    storageBucket: 'jbmtraders-ed3d9.firebasestorage.app',
    measurementId: 'G-4N1JSEQVRE',
  );
}
